<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerKYOxZow\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKYOxZow/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKYOxZow.legacy');
=======
if (\class_exists(\ContainerXR65JAd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXR65JAd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXR65JAd.legacy');
>>>>>>> bf81d60aeabe2054419241afe887874e5d997734

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerKYOxZow\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKYOxZow\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'KYOxZow',
    'container.build_id' => '38ab72ca',
    'container.build_time' => 1545235655,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKYOxZow');
=======
    \class_alias(\ContainerXR65JAd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXR65JAd\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XR65JAd',
    'container.build_id' => '0f5ca4b3',
    'container.build_time' => 1545230282,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXR65JAd');
>>>>>>> bf81d60aeabe2054419241afe887874e5d997734
