<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKYOxZow\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKYOxZow/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKYOxZow.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKYOxZow\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKYOxZow\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'KYOxZow',
    'container.build_id' => '38ab72ca',
    'container.build_time' => 1545235655,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKYOxZow');
