<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXR65JAd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXR65JAd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXR65JAd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXR65JAd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXR65JAd\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XR65JAd',
    'container.build_id' => '0f5ca4b3',
    'container.build_time' => 1545230282,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXR65JAd');
